### ISSUE TITLE
Add outputs

### ISSUE THREAD

**Issue by julienfouilhe** [w9jds/firebase-action#82]
I would like to use this action to deploy to the new beta preview channels using `deploy:channel:${{github.head_ref}}` . But then I would like to get the url that is returned in that command. This action doesn't make it possible unfortunately.

Would it be possible to add outputs so that we can get what's returned by the firebase command?

**Comment by EverettZ** [comment]
I second that. Id like to provide the preview URL among other things.

**Comment by nathang21** [comment]
We use Firebase for our frontend and Cloud Run for our Backend.

Would love to see something similar to this GH action which has a simple url output. 
https://github.com/google-github-actions/deploy-cloudrun#outputs

**Comment by w9jds** [comment]
I have pushed a test of this into master if you would be kind to try it out for your use case and let me know if it works. It should be something like `steps.[id].outputs.response` let me know if this is what you are looking for

**Comment by w9jds** [comment]
This should be live on the latest version now too. Keep in mind that this is the full response that the firebase command spits out. If you want something specific, you will most likely need to parse it out in a later step. Let me know if it meets your needs 🙂

**Comment by grimzy** [comment]
Seems that feature [was removed](https://github.com/w9jds/firebase-action/commit/9ec7761096e04c7578c72d1a11ef700a1292db4c) and README is still outdated 😭

Any updates on what's next to reinstate it? How can we help?

**Comment by lukaas33** [comment]
Also looking for this since the 'official' github action has still not added the deployment of functions
